### ISSUE TITLE
sml2mqtt can't start with current smllib-version

### ISSUE THREAD

**Issue by der-peer** [spacemanspiff2007/sml2mqtt#5]
Hey,
great package 👍. So I can get rid of my own SML-parser (idiot-style bash script).

But installing from scratch with current package versions ends up in error:
```
(venv) me@pvanlage:/opt/sml2mqtt$ sml2mqtt --config /opt/sml2mqtt
Traceback (most recent call last):
  File "/opt/sml2mqtt/venv/bin/sml2mqtt", line 5, in <module>
    from sml2mqtt.main import main
  File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/main.py", line 13, in <module>
    from sml2mqtt.sml_device import Device
  File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/sml_device.py", line 8, in <module>
    from smllib import CrcError, SmlStreamReader
ImportError: cannot import name 'CrcError' from 'smllib' (/opt/sml2mqtt/venv/lib/python3.9/site-packages/smllib/__init__.py)

```

There seems to have been some code refactoring on smllib side. Version 0.7 is the highest working version.
Installing with ```pip install smllib==0.7``` fixes it for now.
I'm working with Python 3.9.

**Comment by spacemanspiff2007** [comment]
How do you install sml2mqtt?
If you install it with pip the [version is properly pinned](https://github.com/spacemanspiff2007/sml2mqtt/blob/0b8ea25936fac9364892ecff73094e1c82b25ac0/requirements_setup.txt#L5)

**Comment by der-peer** [comment]
🤔 maybe I messed it up somehow... first was on Debian 10 (so Python 3.7) trying to install it by following your guide. Gave an error like in #1.
Then updated to Debian 11, to try it again with Python 3.9... but on that second attempt, it didn't install with dependencies. Cleaned up the "venv", retried. Same... had to install dependencies by hand.

Will give it a new try with another machine.

**Comment by spacemanspiff2007** [comment]
Updated to latest version
